spring.application.name=lotto

# Server
server.port=8099

# MySQL DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/lottodb?useSSL=false&serverTimezone=Asia/Manila&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=ushpons08
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Initialize schema.sql on startup
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
